# Generated by Django 3.2.4 on 2021-06-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0002_auto_20210615_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_number',
            field=models.SmallIntegerField(),
        ),
    ]
