# Generated by Django 3.2.4 on 2021-06-16 03:05

from django.db import migrations, models
import script.models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0003_alter_level_level_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='hindi',
            field=models.CharField(max_length=64, validators=[script.models.validate_hindi]),
        ),
    ]
